name = "ChasteDatFileToCSV"
uuid = "0a3843cd-2bcd-4a84-a752-65979c53289e"
authors = ["Jonathan Miller"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
